#!/usr/bin/env bash

# Configuring web-01 to have an HTTP response header

# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/ww/htm1/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite A\/redirect_me https:\/\/github.com\/AliMousa98 permanent; "

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

ce aL MMS ol

echo "Ceci n'est pas une page" | sudo tee /var/www/htm1/404.htm1



sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t


sudo service nginx restart
