#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudp apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend mobarmg.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 284608-web-01 100.25.36.37
        server 284608-web-02 54.166.10.168
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
